(defun make-d (a b)
  (cond
    ((and (= a 0) (= b 0)) 0)
    ((and (= a 0) (= b :x)) 0)
    ((and (= a :x) (= b 0)) 0)
    ((and (= a :x) (= b :x)) :x)
    ((and (= a 1) (= b 1)) 1)
    ((and (= a 1) (= b :x)) 1)
    ((and (= a :x) (= b 1)) 1)
    ((and (= a 1) (= b 0)) :d)
    ((and (= a 0) (= b 1)) :^d)
    (t (error "wrong input"))))
